# Generated by Django 4.1 on 2022-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_cliente_options_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_estoque',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
